# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('תכנון וביצוע', 'התנהלות מקצועית: תכנון וביצוע'), ('מיומנויות עבודה ולמידה', 'התנהלות מקצועית: מיומנויות עבודה ולמידה'), ('עבודה בצוות', 'התנהלות מקצועית: עבודה בצוות'), ('חשיבה וניתוח', 'חשיבה והצגה: חשיבה וניתוח'), ('מיומנויות ביטוי בכתב', 'חשיבה והצגה: מיומנויות ביטוי בכתב'), ('מיומנויות ביטוי בעל פה', 'חשיבה והצגה: מיומנויות ביטוי בעל פה'), ('מוטיבציה והשקעה', 'ערכים: מוטיבציה והשקעה'), ('מצוינות', 'ערכים: מצוינות'), ('יושרה אישית ומקצועית', 'ערכים: יושרה אישית ומקצועית'), ('התאמה למערכת', 'פיקוד ומנהיגות: התאמה למערכת'), ('הנעה והובלה', 'פיקוד ומנהיגות: הנעה והובלה'), ('יוזמה והשפעה', 'פיקוד ומנהיגות: יוזמה והשפעה'), ('השתלבות בקבוצה', 'קבוצה ובין אישי: השתלבות בקבוצה'), ('בין אישי', 'קבוצה ובין אישי: בין אישי'), ('פתיחות', 'קבוצה ובין אישי: פתיחות')], max_length=250)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Good'), ('warning', 'Mediocre'), ('danger', 'Bad')], max_length=250)),
                ('trend', models.CharField(choices=[('U', 'Up'), ('C', 'Constant'), ('D', 'Down')], max_length=250)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_last', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('platoon', models.IntegerField(choices=[(1, 'One'), (2, 'Two')])),
            ],
        ),
        migrations.AddField(
            model_name='cut',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Pupil'),
        ),
    ]
