# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('התנהלות מקצועית', 'התנהלות מקצועית'), ('חשיבה והצגה', 'חשיבה והצגה'), ('ערכים', 'ערכים'), ('פיקוד ומנהיגות', 'פיקוד ומנהיגות'), ('קבוצה ובין אישי', 'קבוצה ובין אישי')], max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='cut',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Parameter'),
        ),
    ]
