# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20170909_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='details',
            field=models.TextField(verbose_name='פירוט'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Parameter', verbose_name='פרמטר'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Pupil', verbose_name='חניך'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='status',
            field=models.CharField(choices=[('success', 'Good'), ('warning', 'Mediocre'), ('danger', 'Bad')], max_length=250, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='trend',
            field=models.CharField(choices=[('U', 'Up'), ('C', 'Constant'), ('D', 'Down')], max_length=250, verbose_name='מגמה'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='updated_by',
            field=models.CharField(max_length=250, verbose_name='עודכן על ידי'),
        ),
    ]
