# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20170916_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='status',
            field=models.CharField(choices=[('success', 'מצוין'), ('warning', 'מתאים'), ('danger', 'דרוש שיפור')], max_length=250, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='trend',
            field=models.CharField(choices=[('U', 'בעלייה'), ('C', 'ללא שינוי'), ('D', 'בירידה')], max_length=250, verbose_name='מגמה'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='platoon',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='year',
            field=models.IntegerField(choices=[(1, 'ראשונה'), (2, 'שנייה')]),
        ),
    ]
