# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20170921_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='category',
            field=models.CharField(choices=[('התנהלות מקצועית', 'התנהלות מקצועית'), ('חשיבה והצגה', 'חשיבה והצגה'), ('ערכים', 'ערכים'), ('פיקוד ומנהיגות', 'פיקוד ומנהיגות'), ('קבוצה ובין אישי', 'קבוצה ובין אישי'), ('אחר', 'אחר')], max_length=250, verbose_name='קטגוריה'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(max_length=250, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='שם פרטי'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='platoon',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], verbose_name='מחלקה'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='year',
            field=models.IntegerField(choices=[(1, 'ראשונה'), (2, 'שנייה')], verbose_name='שנה'),
        ),
    ]
