# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20170921_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='year',
            field=models.IntegerField(choices=[(1, 'א'), (2, 'ב')], verbose_name='שנה'),
        ),
    ]
