# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_pupil_can_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='can_read',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='מורשים'),
        ),
    ]
