# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 08:57
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('panel', '0011_auto_20170927_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='תגיות'),
        ),
    ]
