# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_cut_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='last_name',
        ),
        migrations.AddField(
            model_name='pupil',
            name='name',
            field=models.CharField(default='Null', max_length=250, verbose_name='שם'),
        ),
    ]
