# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20171004_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='name',
            field=models.CharField(max_length=250, verbose_name='שם'),
        ),
    ]
