# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20171004_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='status',
            field=models.CharField(choices=[('primary', 'מתאים ביותר'), ('success', 'מתאים'), ('warning', 'דרוש שיפור'), ('danger', 'לא עובר סף')], max_length=250, verbose_name='סטטוס'),
        ),
    ]
