# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_remove_cut_is_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='parameter',
        ),
        migrations.AddField(
            model_name='cut',
            name='parameter',
            field=models.ManyToManyField(to='panel.Parameter', verbose_name='פרמטר'),
        ),
    ]
