# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_auto_20171018_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='עודכן על ידי'),
        ),
    ]
