# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_auto_20171019_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='trend',
        ),
        migrations.AddField(
            model_name='cut',
            name='private',
            field=models.BooleanField(default=False, verbose_name='עדכון פרטי'),
        ),
        migrations.AlterField(
            model_name='cut',
            name='status',
            field=models.CharField(blank=True, choices=[('primary', 'מתאים ביותר'), ('success', 'מתאים'), ('warning', 'דרוש שיפור'), ('danger', 'לא עובר סף')], max_length=250, verbose_name='סטטוס'),
        ),
    ]
