# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_auto_20171020_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Event'),
        ),
    ]
