# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_auto_20171020_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='event',
        ),
    ]
