# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_event_cuts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cuts',
        ),
        migrations.AddField(
            model_name='cut',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.Event'),
        ),
    ]
