# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_auto_20171020_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='cuts',
            field=models.ManyToManyField(to='panel.Cut', verbose_name='פרמטרים'),
        ),
    ]
