# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0033_auto_20171023_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='goals',
            field=models.ManyToManyField(blank=True, to='panel.Parameter'),
        ),
    ]
