# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0034_pupil_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='details',
            field=models.TextField(blank=True, verbose_name='פרטים'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='goals',
            field=models.ManyToManyField(blank=True, to='panel.Parameter', verbose_name='יעדים'),
        ),
    ]
