# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20171110_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
    ]
