# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20171113_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='דד-ליין'),
        ),
    ]
